//
//  AqsaViewModel.swift
//  AlAqsaExpandingView
// m7606225@gmail.com
//  Created by Mohammed Abunada on 2020-06-22.
//  Copyright © 2020 NMDS. All rights reserved.
// https://github.com/m760622

import SwiftUI

// The Model of Item
struct Item : Identifiable {
    var id = UUID()
    var title : String
    var subTitle : String
    var image : String
    var content : String
}//Item

//The Array
var aqsaDB = [
    Item(title: "'Painful': Al-Aqsa closed for Ramadan over coronavirus", subTitle: "1", image: "alaqsa01", content: "Jerusalem's Al-Aqsa mosque compound will be closed to Muslim worshippers throughout the holy fasting month of Ramadan due to the coronavirus pandemic, Muslim clerics at Islam's third-holiest site have announced. \nJerusalem Islamic Waqf, the Jordan-appointed council that oversees Islamic sites on the sacred compound, called the decision \"painful\"."),
    Item(title: "Why al-Aqsa is so important?", subTitle: "2", image: "alaqsa02", content: "Al-Aqsa is the name of the silver-domed mosque inside a 35-acre compound referred to as al-Haram al-Sharif, or the Noble Sanctuary, by Muslims, and as the Temple Mount by Jews. The compound lies in the Old City of Jerusalem, which has been designated a World Heritage site by the United Nations cultural agency, UNESCO, and is important to the three Abrahamic religions.\nThe site has been the most contested piece of territory in the Holy Land since Israel occupied East Jerusalem, including the Old City, in 1967, along with the West Bank and Gaza Strip. However, the conflict dates even further back, to before the creation of Israel.\nIn 1947, the UN drew up a partition plan to separate historical Palestine, then under British control, into two states: one for Jews, mainly from Europe, and one for Palestinians. The Jewish state was given 55 percent of the land, and the remaining 45 percent was for a Palestinian state.\nJerusalem, which houses the al-Aqsa compound, belonged to the international community under the administration of the UN. It was granted this special status for its importance to the three Abrahamic religions.\nThe first Arab-Israeli war broke out in 1948 after Israel declared statehood, capturing some 78 percent of the land, with the remaining areas of the West Bank, East Jerusalem and Gaza coming under Egyptian and Jordanian control.\nIsrael's increasing encroachment on the land intensified in 1967, after the second Arab-Israeli war, which resulted in the Israeli occupation of East Jerusalem, and eventually the illegal Israeli annexation of Jerusalem, including the Old City and al-Aqsa."),
    Item(title: "Historical Palestine", subTitle: "3", image: "alaqsa03", content: "In 1947, the UN drew up a partition plan to separate historical Palestine, then under British control, into two states: one for Jews, mainly from Europe, and one for Palestinians. The Jewish state was given 55 percent of the land, and the remaining 45 percent was for a Palestinian state.\nJerusalem, which houses the al-Aqsa compound, belonged to the international community under the administration of the UN. It was granted this special status for its importance to the three Abrahamic religions."),
    Item(title: "The compound's religious significance", subTitle: "4", image: "alaqsa04", content: "For Muslims, the Noble Sanctuary hosts Islam's third holiest site, the al-Aqsa Mosque, and the Dome of the Rock, a seventh-century structure believed to be where the Prophet Muhammad ascended to heaven.\nJews believe the compound is where the Biblical Jewish temples once stood, but Jewish law and the Israeli Rabbinate forbid Jews from entering the compound and praying there, as it is considered too holy to tread upon."),
    Item(title: "The site's status quo", subTitle: "5", image: "alaqsa05", content: "Since 1967, Jordan and Israel agreed that the Waqf, or the Islamic trust, would have control over matters inside the compound, while Israel would control external security. Non-Muslims would be allowed onto the site during visiting hours, but would not be allowed to pray there.\nBut rising Temple movements, such as the Temple Mount Faithful and the Temple Institute, have challenged the Israeli government's ban on allowing Jews to enter the compound, and they aim to rebuild the Third Jewish Temple in the compound.\nSuch groups are funded by members of the Israeli government, though it claims a desire to maintain the status quo at the site. "),
    Item(title: "How Israel occupied the whole of Palestine in 1967", subTitle: "6", image: "alaqsa06", content: "More than 50 years ago, the state of Israel shocked the world when it seized the remaining Palestinian territories of the West Bank, East Jerusalem, Gaza Strip, as well as the Syrian Golan Heights and the Egyptian Sinai Peninsula, in a matter of six days.\nIn a war with Egypt, Jordan and Syria, known as the 1967 War, or the June War, Israel delivered what came to be known as the \"Naksa\", meaning setback or defeat, to the armies of the neighbouring Arab countries, and to the Palestinians who lost all what remained of their homeland."),
    Item(title: "Recent tensions ", subTitle: "7", image: "alaqsa07", content: "Tensions have been simmering near al-Aqsa for the past two years. In 2015, clashes broke out after hundreds of Jews tried to enter the mosque complex to commemorate a Jewish holiday.\nA year later, protests also erupted after visits by groups of Jewish settlers to the compound during the last 10 days of Islam's holy month of Ramadan, in contravention of tradition.\nMost clashes in the compound have occurred because of Israeli settlers trying to pray within the compound, which directly violates the status quo.\nTensions have risen after Israel shut down al-Aqsa Mosque compound for the first time since 1969, after a deadly gun battle between Palestinian citizens of Israel and Israeli forces."),
    Item(title: "During Friday prayers in July 2017", subTitle: "8", image: "alaqsa08", content: "Thousands of Palestinians came out to pray in the streets outside of Lion's Gate, one of the entrances to the Old City. Tension raged after peaceful demonstrations were violently suppressed by Israeli forces, resulting in hundreds of injuries. Four Palestinians were shot dead in occupied East Jerusalem and the West Bank, one of whom was shot by an Israeli settler."),
    Item(title: "The greater context", subTitle: "9", image: "alaqsa09", content: "Al-Aqsa is a small area within Palestine, but symbolically it is a large part of the conflict between Israelis and Palestinians.\nThough the mosque itself is significant for Muslims especially, Palestinian Christians have also protested against Israeli encroachment on the compound, joining Muslims in prayer outside Lion's Gate on Friday."),
    Item(title: "The issue of al-Haram al-Sharif stands as a symbolic", subTitle: "10", image: "alaqsa10", content: "The issue of al-Haram al-Sharif stands as a symbolic, but very strong catalyser of the routine of injustice and oppression that Palestinians in Jerusalem are facing, and that causes a continuous eruption of popular anger and uprisings, Yara Jalajel, a former legal adviser to the Palestinian minister of foreign affairs, told Al Jazeera in July 2017.\nWith more restrictions placed on Palestinian access to the compound and ongoing calls by Israeli religious groups to allow Jews to pray at the site, many Palestinians fear a possible division of the compound."),
    Item(title: "Palestinians in Jerusalem", subTitle: "11", image: "alaqsa11", content: "Who number around 400,000, hold only permanent residency status, not citizenship, despite being born there - in contrast with Jews who are born in the city. And, since 1967, Israel has embarked on a quiet deportation of the city's Palestinians by imposing difficult conditions for them to maintain their residency status.\nIsrael has also built at least 12 fortified Jewish-only illegal settlements in East Jerusalem, housing some 200,000 Israelis, while rejecting Palestinian building permits and demolishing their homes as punishment for building illegally."),
    Item(title: "The Temple Mount Faithful", subTitle: "12", image: "alaqsa12", content: "In 1990, the Temple Mount Faithful declared it would lay a cornerstone for the Third Temple in place of the Dome of the Rock, leading to riots and a massacre in which 20 Palestinians were killed by Israeli police. \nIn 2000, Israeli politician Ariel Sharon entered the holy site accompanied by some 1,000 Israeli police, deliberately reiterating Israeli claims to the contested area in light of then Prime Minister Ehud Barak's US-brokered peace negotiations with Palestinian leader Yasser Arafat, which included discussions on how the two sides could share Jerusalem. Sharon's entrance to the compound unleashed the Second Intifada, in which more than 3,000 Palestinians and some 1,000 Israelis were killed.  In May 2017, the Israeli cabinet held its weekly meeting in tunnels below al-Aqsa Mosque, on the 50th anniversary of the Israeli occupation of East Jerusalem, \"to mark the liberation and unification of Jerusalem\" - a move that infuriated Palestinians.\nIsrael already restricts Palestinian entry into the compound through several methods, including the separation wall, built in the early 2000s, which restricts the entry of Palestinians from the West Bank into Israel. \nOf the three million Palestinians in the occupied West Bank, only those over a certain age are allowed access to Jerusalem on Fridays, while others must apply for a hard-to-obtain permit from Israeli authorities. The restrictions already cause serious congestion and tension at checkpoints between the West Bank and Jerusalem, where tens of thousands must pass through security checks to enter Jerusalem to pray."),
    Item(title: "'Painful': Al-Aqsa closed for Ramadan over coronavirus", subTitle: "13", image: "alaqsa13", content: "Jerusalem's Al-Aqsa mosque compound will be closed to Muslim worshippers throughout the holy fasting month of Ramadan due to the coronavirus pandemic, Muslim clerics at Islam's third-holiest site have announced. \nJerusalem Islamic Waqf, the Jordan-appointed council that oversees Islamic sites on the sacred compound, called the decision \"painful\".")
]

//The ViewModel
class AqsaViewModel: NSObject, ObservableObject {
    @Published var aqsaArray = [Item]()
    override init() {
        aqsaArray = aqsaDB
    }
}//AqsaViewModel

